### ISSUE TITLE
SAML tab missing on Chrome homepages

### ISSUE THREAD

**Issue by danieltaylor** [milton-lai/saml-chrome-panel#11]
If I open dev tools while on a Chrome homepage and then navigate to a site, the SAML tab fails to show up.  I can either close dev tools and reopen it, or wait until navigating to a site to open dev tools, but this becomes a pain, especially in cases where the site I'm testing sends a SAML request on load.  If I remember correctly, there was a time where the SAML tab was able to load even on homepages.  This issue seems similar to the one discussed in issue #8.  Thank you for creating this tool and for any help anyone is able to provide!

**Comment by milton-lai** [comment]
Hi @danieltaylor,
I just tried it and it seems more like a Chrome issue.
I get what you're saying.
If its a new tab / window, then I get this:
![image](https://github.com/milton-lai/saml-chrome-panel/assets/13580442/06772ba3-5aa4-46f4-b8e3-e3c5c2223a8c)
If I visit a site, then I get this:
![image](https://github.com/milton-lai/saml-chrome-panel/assets/13580442/39a2bcb6-d345-4f4d-a0f0-fa399711807a)

As you can see, "Redux" and "Adblock" are doing the same thing, which makes me think its a Google Chrome change, rather than something I can fully control.

I will try to take a look, but I suspect we may need to wait for Chrome to fix it...

I'll keep the open to see if I have an update in the next week.

**Comment by xsrf** [comment]
Hey, for months now the Tab is completely gone for me in devtools and I have no clue how to get it back. Regardless if I navigate sites with devtools open or not. The extension is active and has access to the site. It worked before™. I already reinstalled the extension.
Any idea how to debug this? The extension was really helpful :(

**Comment by milton-lai** [comment]
Hey @xsrf - what version of Chrome are you using? I've confirmed at least that 119.0.6045.159 is working on MacOS.

**Comment by xsrf** [comment]
Version 119.0.6045.160 on Windows 10

**Comment by milton-lai** [comment]
Thanks @xsrf . Are you able to install Redux (https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) and see if that one appears? I did have correlation with other extensions, when they didnt show, neither did mine (e.g. Chrome is the cause of the issue).

**Comment by xsrf** [comment]
@milton-lai Redux works. I just noticed the SAML Tab also shows up in inkognito mode and also works fine in new user profiles in chrome. Looks like it's an issue with my user profile. Disabling all other extensions didn't help. Kinda strange...

**Comment by milton-lai** [comment]
Thank you for trying that out. Interesting - I do have 2 profiles, one for work and one personal. My personal has SAML chrome extension installed, but when I'm on my work profile, it isn't and won't show. Not sure if theres jumbling up of profiles?

**Comment by xsrf** [comment]
@milton-lai I had to install it on every profile separately of course. For me the issue is solved, sorry for the confusion and hijacking this issue. It clearly just affects my one profile and is not reproducible in any way. I don't expect a solution to this here. I'm fine with using inkognito mode for now until I may reinstall chrome / windows.

**Comment by milton-lai** [comment]
Partially solved =) but good to know and thanks for going through the steps. I wish I had better ways to debug it! My last change was moving everything over to the latest manifest version, so at least its up to date.
Good luck, but if you find any info, keep us posted!
